services:
  geobit:
    container_name: geobit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV_TYPE=production
      - RUNNING_IN_DOCKER=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - geobit-network

networks:
  geobit-network:
    name: geobit-network
    driver: bridge
  geobit-infra-network:
    name: geobit-infra-network
    driver: bridge
