services:
  fastapi-template:
    container_name: fastapi-template
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV_TYPE=production
      - RUNNING_IN_DOCKER=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - fastapi-template-network

networks:
  fastapi-template-network:
    name: fastapi-template-network
    driver: bridge
  fastapi-template-infra-network:
    name: fastapi-template-infra-network
    driver: bridge 